/**
 * Freely-licensed reference photos, one per park, from Wikimedia Commons.
 *
 * GENERATED by scripts/fetch-park-photos.mjs from a hand-reviewed pick list --
 * edit scripts/photo-harvest/picks.json and re-run rather than editing this file.
 *
 * These are stand-ins shown until the couple publish a photo of their own for
 * that park, at which point theirs wins. Every entry is CC BY, CC BY-SA, CC0 or
 * public domain, and the first two of those require the author and licence to
 * be shown wherever the image is. The credit is a condition of use, not
 * decoration: do not remove it, and do not add an image here without one.
 *
 * Parks with no entry had no usable free photo taken from behind home plate.
 * That is deliberate -- the slot stays empty rather than showing the wrong shot.
 */
export interface ReferencePhoto {
  file: string;
  author: string;
  licence: string;
  licenceUrl: string | null;
  sourceUrl: string;
}

export const referencePhotos: Record<string, ReferencePhoto> = {
  "camden": {
    file: "/img/parks/camden.webp",
    author: "Aspifi",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:OrioleParkatCamdenYardsSummer2025.jpg",
  },
  "fenway": {
    file: "/img/parks/fenway.webp",
    author: "Rick Berry",
    licence: "Public domain",
    licenceUrl: null,
    sourceUrl: "https://commons.wikimedia.org/wiki/File:131023-F-PR861-033_Hanscom_participates_in_World_Series_pregame_events.jpg",
  },
  "yankee": {
    file: "/img/parks/yankee.webp",
    author: "vtravelled.com",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yankee_Stadium_overhead_2010.jpg",
  },
  "tropicana": {
    file: "/img/parks/tropicana.webp",
    author: "Vmartin12",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:PXL_20220528_205520913.jpg",
  },
  "rogers": {
    file: "/img/parks/rogers.webp",
    author: "JFVoll",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rogers_Centre_(500_Level)_-_Toronto,_ON.jpg",
  },
  "rate": {
    file: "/img/parks/rate.webp",
    author: "Another Believer",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chicago,_Illinois,_U.S._(2023)_-_062.jpg",
  },
  "comerica": {
    file: "/img/parks/comerica.webp",
    author: "User MJCdetroit on en.wikipedia",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Detroit_Tigers_opening_game_at_Comerica_Park,_2007.jpg",
  },
  "kauffman": {
    file: "/img/parks/kauffman.webp",
    author: "Chibears85",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kauffman2017.jpg",
  },
  "target": {
    file: "/img/parks/target.webp",
    author: "Ken Lund from Reno, Nevada, USA",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Target_Field,_Minneapolis,_Minnesota_(43167053335).jpg",
  },
  "daikin": {
    file: "/img/parks/daikin.webp",
    author: "User Blwarren713 on en.wikipedia",
    licence: "CC BY 2.5",
    licenceUrl: "https://creativecommons.org/licenses/by/2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Astros.opening.day.2007.intros.jpg",
  },
  "angel": {
    file: "/img/parks/angel.webp",
    author: "CrispyCream27",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Angelstadiummarch2019.jpg",
  },
  "tmobile": {
    file: "/img/parks/tmobile.webp",
    author: "MyName (Cacophony)",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SafecoFieldTop.jpg",
  },
  "truist": {
    file: "/img/parks/truist.webp",
    author: "TarheelBornBred",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Truist_Park_2025.jpg",
  },
  "loandepot": {
    file: "/img/parks/loandepot.webp",
    author: "Ven-Lib",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:LOAN_DEPOT_PARK.jpg",
  },
  "nationals": {
    file: "/img/parks/nationals.webp",
    author: "APK",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nationals_Park_8.16.19_-_7.jpg",
  },
  "wrigley": {
    file: "/img/parks/wrigley.webp",
    author: "Sea Cow",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wrigley_Field_in_line_with_sign.jpg",
  },
  "gabp": {
    file: "/img/parks/gabp.webp",
    author: "Laslovarga",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:10Cincinnati_2015_(2).jpg",
  },
  "amfam": {
    file: "/img/parks/amfam.webp",
    author: "Corey Coyle",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ATC_Power_Lines_%5E_Miller_Park_-_panoramio.jpg",
  },
  "pnc": {
    file: "/img/parks/pnc.webp",
    author: "Joshua Peacock jcpeacock",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pittsburgh_Pirates_park_(Unsplash).jpg",
  },
  "busch": {
    file: "/img/parks/busch.webp",
    author: "Lightmetro",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Busch_Stadium_2022.jpg",
  },
  "chase": {
    file: "/img/parks/chase.webp",
    author: "U.S. Air Force photo by Staff Sgt. Tyler J. Bolken",
    licence: "Public domain",
    licenceUrl: null,
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Reserve_A-10_Warthogs_Flyover_2023_World_Series_(8099146).jpg",
  },
  "dodger": {
    file: "/img/parks/dodger.webp",
    author: "Spatms",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dodger_Stadium_and_Chavez_Ravine_far_view,_Chicago_Cubs_at_Los_Angeles_Dodgers,_(April_12,_2025).jpg",
  },
  "petco": {
    file: "/img/parks/petco.webp",
    author: "Mds08011",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Petco_Park_Padres_Game.jpg",
  },
  "oracle": {
    file: "/img/parks/oracle.webp",
    author: "Chris6d",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Oracle_Park_2021.jpg",
  },
  "steinbrenner": {
    file: "/img/parks/steinbrenner.webp",
    author: "Lonelykicker17",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SFPan.jpg",
  },
  "globelife": {
    file: "/img/parks/globelife.webp",
    author: "Ivansevil",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:20210523_globe_life_field_interior.jpg",
  },
  "coors": {
    file: "/img/parks/coors.webp",
    author: "DimiTalen",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:4th_of_July_Colorado_Rockies_-_Arizona_Diamondbacks_game,_Coors_Field,_Denver,_2009.jpg",
  },
  "sutter": {
    file: "/img/parks/sutter.webp",
    author: "Quintin Soloviev",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sutter_Health_Park_in_Sacramento,_CA.jpg",
  },
};
